-- Hallazgo 14: los eventos se guardan en la misma transacción que el cambio de estado y se publican después.
create table outbox (
    id           bigint generated by default as identity primary key,
    event_id     uuid                     not null,
    tipo         varchar(60)              not null,
    payload      text                     not null,
    creado_en    timestamp with time zone not null,
    publicado_en timestamp with time zone
);

create index ix_outbox_pendientes on outbox (publicado_en, id);

-- Hallazgo 12: sesión de LiveKit (participant sid) que publica el video, para reconocer su salida por webhook.
alter table transmision add column emisor_sid varchar(64);
